events {}
http {
    include /etc/nginx/mime.types;
    server {
        listen 80;
        client_max_body_size 1m;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        location = /api/v2/notifications { return 308 /api/v2/notifications/; }
        location /api/v2/notifications/ {
            proxy_pass http://notifications:5000;
        }
        location /api/v1/ {
            proxy_pass http://django:8000;
        }
        location /static/ { alias /static/; }
        location / {
            proxy_pass http://django:8000;
        }
    }
}
